//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeomSoft.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCurrency
    {
        public int AccountCurrencyID { get; set; }
        public int AccountID { get; set; }
        public int CurrencyID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Account Account { get; set; }
    }
}
